import type { AgotFactionCode} from '../agot.models';
import { agotAgendaCode as agenda } from '../agot.models';

export interface AgotFcDeck {
  id: string;
  name: string;
  faction: AgotFactionCode;
  agenda: string;
  link?: string;
}

export const DECKS: AgotFcDeck[] = [
  {
    id: 'FCD 01/40',
    name: 'House Stark, Fealty',
    faction: 'stark',
    agenda: agenda.Fealty,
  },
  {
    id: 'FCD 02/40',
    name: 'House Stark, Kings of Winter',
    faction: 'stark',
    agenda: agenda.KingsOfWinter,
    link: 'https://thronesdb.com/decklist/view/15769/fcd-02-40-house-stark-kings-of-winter-1.0',
  },
  {
    id: 'FCD 03/40',
    name: 'House Stark, The Lord of the Crossing',
    faction: 'stark',
    agenda: agenda.TheLordOfTheCrossing,
    link: 'https://thronesdb.com/decklist/view/15768/fcd-03-40-house-stark-the-lord-of-the-crossing-1.0',
  },
  {
    id: 'FCD 04/40',
    name: 'House Stark, Trading With Qohor',
    faction: 'stark',
    agenda: agenda.TradingWithQohor,
  },
  {
    id: 'FCD 05/40',
    name: 'House Stark, The Faith Militant',
    faction: 'stark',
    agenda: agenda.TheFaithMilitant,
    link: 'https://thronesdb.com/decklist/view/15763/fcd-05-40-house-stark-the-faith-militant-1.0',
  },
  {
    id: 'FCD 06/40',
    name: 'House Lannister, "The Rains of Castamere"',
    faction: 'lannister',
    agenda: agenda.TheRainsOfCastamere,
  },
  {
    id: 'FCD 07/40',
    name: 'House Lannister, The Lord of the Crossing',
    faction: 'lannister',
    agenda: agenda.TheLordOfTheCrossing,
    link: 'https://thronesdb.com/decklist/view/15777/fcd-07-40-house-lannister-the-lord-of-the-crossing-1.0',
  },
  {
    id: 'FCD 08/40',
    name: 'House Lannister, The White Book',
    faction: 'lannister',
    agenda: agenda.TheWhiteBook,
    link: 'https://thronesdb.com/decklist/view/15764/fcd-08-40-house-lannister-the-white-book-1.0',
  },
  {
    id: 'FCD 09/40',
    name: 'House Lannister, Kingdom of Shadows',
    faction: 'lannister',
    agenda: agenda.KingdomOfShadows,
  },
  {
    id: 'FCD 10/40',
    name: 'House Lannister, Alliance',
    faction: 'lannister',
    agenda: agenda.Alliance,
    link: 'https://thronesdb.com/decklist/view/15771/fcd-10-40-house-lannister-alliance-1.0',
  },
  {
    id: 'FCD 11/40',
    name: "The Night's Watch, Greensight",
    faction: 'thenightswatch',
    agenda: agenda.Greensight,
    link: 'https://thronesdb.com/decklist/view/15761/fcd-11-40-the-night-s-watch-greensight-1.0',
  },
  {
    id: 'FCD 12/40',
    name: "The Night's Watch, Fealty",
    faction: 'thenightswatch',
    agenda: agenda.Fealty,
    link: 'https://thronesdb.com/decklist/view/15772/fcd-12-40-the-night-s-watch-fealty-1.0',
  },
  {
    id: 'FCD 13/40',
    name: "The Night's Watch, Knights of the Hollow Hill",
    faction: 'thenightswatch',
    agenda: agenda.KnightsOfTheHollowHill,
    link: 'https://thronesdb.com/decklist/view/15779/fcd-13-40-the-night-s-watch-knights-of-the-hollow-hill-1.0',
  },
  {
    id: 'FCD 14/40',
    name: "The Night's Watch, Valyrian Steel",
    faction: 'thenightswatch',
    agenda: agenda.ValyrianSteel,
  },
  {
    id: 'FCD 15/40',
    name: "The Night's Watch, The Conclave",
    faction: 'thenightswatch',
    agenda: agenda.TheConclave,
    link: 'https://thronesdb.com/decklist/view/15774/fcd-15-40-the-night-s-watch-the-conclave-1.0',
  },
  {
    id: 'FCD 16/40',
    name: 'House Tyrell, Kings of Summer',
    faction: 'tyrell',
    agenda: agenda.KingsOfSummer,
    link: 'https://thronesdb.com/decklist/view/15776/fcd-16-40-house-tyrell-kings-of-summer-1.0',
  },
  {
    id: 'FCD 17/40',
    name: 'House Tyrell, "The Rains of Castamere"',
    faction: 'tyrell',
    agenda: agenda.TheRainsOfCastamere,
  },
  {
    id: 'FCD 18/40',
    name: 'House Tyrell, Assault from the Shadows',
    faction: 'tyrell',
    agenda: agenda.AssaultFromTheShadows,
    link: 'https://thronesdb.com/decklist/view/15767/fcd-18-40-house-tyrell-assault-from-the-shadows-1.0',
  },
  {
    id: 'FCD 19/40',
    name: 'House Tyrell, The Wars To Come',
    faction: 'tyrell',
    agenda: agenda.TheWarsToCome,
    link: 'https://thronesdb.com/decklist/view/15760/fcd-19-40-house-tyrell-the-wars-to-come-1.0',
  },
  {
    id: 'FCD 20/40',
    name: 'House Tyrell, Alliance',
    faction: 'tyrell',
    agenda: agenda.Alliance,
  },
  {
    id: 'FCD 21/40',
    name: 'House Martell, Knights of the Hollow Hill',
    faction: 'martell',
    agenda: agenda.KnightsOfTheHollowHill,
  },
  {
    id: 'FCD 22/40',
    name: 'House Martell, Kings of Summer',
    faction: 'martell',
    agenda: agenda.KingsOfSummer,
    link: 'https://thronesdb.com/decklist/view/15770/fcd-22-40-house-martell-kings-of-summer-1.0',
  },
  {
    id: 'FCD 23/40',
    name: 'House Martell, The Wars To Come',
    faction: 'martell',
    agenda: agenda.TheWarsToCome,
  },
  {
    id: 'FCD 24/40',
    name: 'House Martell, The Lord of the Crossing',
    faction: 'martell',
    agenda: agenda.TheLordOfTheCrossing,
    link: 'https://thronesdb.com/decklist/view/15765/fcd-24-40-house-martell-the-lord-of-the-crossing-1.0',
  },
  {
    id: 'FCD 25/40',
    name: 'House Martell, Kingdom of Shadows',
    faction: 'martell',
    agenda: agenda.KingdomOfShadows,
  },
  {
    id: 'FCD 26/40',
    name: 'House Greyjoy, Kings of Winter',
    faction: 'greyjoy',
    agenda: agenda.KingsOfWinter,
    link: 'https://thronesdb.com/decklist/view/15778/fcd-26-40-house-greyjoy-kings-of-winter-1.0',
  },
  {
    id: 'FCD 27/40',
    name: 'House Greyjoy, Sea of Blood',
    faction: 'greyjoy',
    agenda: agenda.SeaOfBlood,
  },
  {
    id: 'FCD 28/40',
    name: 'House Greyjoy, Greensight',
    faction: 'greyjoy',
    agenda: agenda.Greensight,
    link: 'https://thronesdb.com/decklist/view/15762/fcd-28-40-house-greyjoy-greensight-1.0',
  },
  {
    id: 'FCD 29/40',
    name: 'House Greyjoy, Valyrian Steel',
    faction: 'greyjoy',
    agenda: agenda.ValyrianSteel,
  },
  {
    id: 'FCD 30/40',
    name: 'House Greyjoy, The Free Folk',
    faction: 'greyjoy',
    agenda: agenda.TheFreeFolk,
  },
  {
    id: 'FCD 31/40',
    name: 'House Baratheon, Fealty',
    faction: 'baratheon',
    agenda: agenda.Fealty,
  },
  {
    id: 'FCD 32/40',
    name: 'House Baratheon, The Prince that was Promised',
    faction: 'baratheon',
    agenda: agenda.ThePrinceThatWasPromised,
    link: 'https://thronesdb.com/decklist/view/15775/fcd-32-40-house-baratheon-the-prince-that-was-promised-1.0',
  },
  {
    id: 'FCD 33/40',
    name: 'House Baratheon, Assault from the Shadows',
    faction: 'baratheon',
    agenda: agenda.AssaultFromTheShadows,
  },
  {
    id: 'FCD 34/40',
    name: 'House Baratheon, The House With the Red Door',
    faction: 'baratheon',
    agenda: agenda.TheHouseWithTheRedDoor,
    link: 'https://thronesdb.com/decklist/view/15766/fcd-34-40-house-baratheon-the-house-with-the-red-door-1.0',
  },
  {
    id: 'FCD 35/40',
    name: 'House Baratheon, The Brotherhood Without Banners',
    faction: 'baratheon',
    agenda: agenda.TheBrotherhoodWithoutBanners,
    link: 'https://thronesdb.com/decklist/view/15773/fcd-35-40-house-baratheon-the-brotherhood-without-banners-1.0',
  },
  {
    id: 'FCD 36/40',
    name: 'House Targaryen, The House With the Red Door',
    faction: 'targaryen',
    agenda: agenda.TheHouseWithTheRedDoor,
    link: 'https://thronesdb.com/decklist/view/15781/fcd-36-40-house-targaryen-the-house-with-the-red-door-1.0',
  },
  {
    id: 'FCD 37/40',
    name: 'House Targaryen, Trading With Qohor',
    faction: 'targaryen',
    agenda: agenda.TradingWithQohor,
    link: 'https://thronesdb.com/decklist/view/15780/fcd-37-40-house-targaryen-trading-with-qohor-1.0',
  },
  {
    id: 'FCD 38/40',
    name: 'House Targaryen, Sea of Blood',
    faction: 'targaryen',
    agenda: agenda.SeaOfBlood,
  },
  {
    id: 'FCD 39/40',
    name: 'House Targaryen, The Prince that was Promised',
    faction: 'targaryen',
    agenda: agenda.ThePrinceThatWasPromised,
    link: 'https://thronesdb.com/decklist/view/15782/fcd-39-40-house-targaryen-the-prince-that-was-promised-1.0',
  },
  {
    id: 'FCD 40/40',
    name: 'House Targaryen, Alliance',
    faction: 'targaryen',
    agenda: agenda.Alliance,
  },
];
