/* eslint-disable max-statements-per-line */
/* eslint-disable @typescript-eslint/no-shadow */
// https://www.youtube.com/watch?v=eW9mZqSWKCA&list=PL5jW5oNoeQ7ruXxk1EaQMqeJzE50eECSu&ab_channel=WaroftheRingChamp

import { discardDice } from "../action-die/wotr-action-die-actions";
import { WotrActionToken } from "../action-token/wotr-action-token.models";
import { attack, combatCard, continueBattle, forfeitLeadership, noCombatCard, reRollCombatDice, retreat, retreatIntoSiege, rollCombatDice } from "../battle/wotr-battle-actions";
import { discardCards, discardRandomCard, drawCards, playCardOnTable } from "../card/wotr-card-actions";
import { chooseRandomCompanion, eliminateCharacter, moveCharacters, playCharacter, separateCompanions } from "../companion/wotr-character-actions";
import { changeGuide, corruptFellowship, declareFellowship, healFellowship, hideFellowship, moveFelloswhip, notDeclareFellowship, revealFellowship } from "../fellowship/wotr-fellowship-actions";
import { WotrFreePeoplesStoryComposer, WotrShadowStoryComposer, WotrStoryDoc } from "../game/wotr-story.models";
import { addHuntTile, drawHuntTile, reRollHuntDice, rollHuntDice } from "../hunt/wotr-hunt-actions";
import { advanceNation } from "../nation/wotr-political-actions";
import { character, eliminateEliteUnit, eliminateLeader, eliminateRegularUnit, elite, moveAllArmy, moveArmy, moveNazgul, nazgul, recruitEliteUnit, recruitRegularUnit, regular } from "../unit/wotr-unit-actions";

let time = 1;
export const stories: WotrStoryDoc[] = [
  // Turn 1
  fp (time).phaseStory (drawCards ("The Power of Tom Bombadil", "Elven Cloaks")),
  s ().phaseStory (drawCards ("The Day Without Dawn", "Worn with Sorrow and Toil")),
  fp ().phaseStory (notDeclareFellowship ()),
  s ().huntAllocation (1),
  fp (time).rollActionDice ("character", "character", "muster-army", "muster"),
  s ().rollActionDice ("army", "character", "army", "character", "event", "eye"),
  fp ().pass (),
  s ().characterDie (moveAllArmy ("barad-dur", "gorgoroth")),
  fp ().characterDie (moveFelloswhip ()),
  s ().phaseStory (rollHuntDice (1, 6)),
  s ().phaseStory (drawHuntTile ("3")),
  fp ().phaseStory (eliminateCharacter ("gandalf-the-grey"), changeGuide ("strider")),
  s ().eventDieCard ("Worn with Sorrow and Toil", playCardOnTable ("Worn with Sorrow and Toil")),
  fp ().characterDie (moveFelloswhip ()),
  s ().phaseStory (rollHuntDice (5, 2)),
  s ().phaseStory (drawHuntTile ("1")),
  fp ().phaseStory (corruptFellowship (1)),
  s ().characterDie (moveArmy ("gorgoroth", "morannon", regular ("sauron", 4), elite ("sauron"), nazgul ())),
  fp ().musterArmyDie (
    moveAllArmy ("carrock", "old-forest-road"),
    moveAllArmy ("edoras", "westemnet")),
  s ().armyDie (
    moveArmy ("dol-guldur", "north-anduin-vale", regular ("sauron", 4), elite ("sauron"), nazgul ()),
    moveAllArmy ("morannon", "dagorlad")),
  fp ().musterDie (advanceNation ("elves", 1)),
  s ().armyDie (
    moveAllArmy ("north-anduin-vale", "dimrill-dale"),
    moveAllArmy ("dagorlad", "noman-lands")),
  fp ().actionToken ("political-advance", advanceNation ("elves", 1)),
  fp ().skipTokens (),
  // Turn 2
  fp (time).phaseStory (drawCards ("The Ents Awake: Entmoot", "Kindred of Glorfindel")),
  s ().phaseStory (drawCards ("Return to Valinor", "Nazgul Search")),
  fp ().phaseStory (notDeclareFellowship ()),
  s ().huntAllocation (1),
  fp (time).rollActionDice ("muster-army", "character", "event", "will-of-the-west"),
  s ().rollActionDice ("event", "muster-army", "event", "army", "event"),
  fp ().pass (),
  s ().eventDie (drawCards ("Rage of the Dunledings")),
  fp ().eventDieCard ("Elven Cloaks", addHuntTile ("b0")),
  s ().eventDie (drawCards ("The Fighting Uruk-hai")),
  fp ().characterDie (moveFelloswhip ()),
  s ().huntStory (rollHuntDice (6, 2)),
  s ().huntStory (drawHuntTile ("er")),
  fp ().huntStory (corruptFellowship (1)),
  fp ().huntStory (revealFellowship ("goblins-gate")),
  s ().musterArmyDie (advanceNation ("isengard")),
  fp ().musterArmyDie (hideFellowship ()),
  s ().eventDieCard ("Rage of the Dunledings",
    recruitRegularUnit ("moria", "isengard", 2),
    moveAllArmy ("south-dunland", "moria"),
    moveAllArmy ("north-dunland", "moria")),
  fp ().willOfTheWestDie (moveFelloswhip ()),
  s ().huntStory (rollHuntDice (2, 6)),
  s ().huntStory (drawHuntTile ("3")),
  fp ().huntStory (chooseRandomCompanion ("strider")),
  fp ().huntStory (eliminateCharacter ("strider"), changeGuide ("legolas")),
  s ().cardReaction ("Worn with Sorrow and Toil", discardRandomCard ("The Ents Awake: Entmoot")),
  s ().armyDie (
    moveArmy ("moria", "dimrill-dale", regular ("sauron", 1), regular ("isengard", 4)),
    moveAllArmy ("noman-lands", "southern-rhovanion")),
  fp ().skipTokens (),
  // Turn 3
  fp (time).phaseStory (drawCards ("Celeborn's Galadhrim", "Mithril Coat and Sting")),
  s ().phaseStory (drawCards ("Half-orcs and Goblin-men", "Wormtongue")),
  fp ().phaseStory (notDeclareFellowship ()),
  s ().huntAllocation (1),
  fp (time).rollActionDice ("will-of-the-west", "muster-army", "character", "event"),
  s ().rollActionDice ("muster", "muster", "event", "event", "muster-army", "army"),
  fp ().characterDie (moveFelloswhip ()),
  s ().huntStory (rollHuntDice (1)),
  s ().musterDie (advanceNation ("sauron")),
  fp ().pass (),
  s ().armyDie (
    moveAllArmy ("southern-rhovanion", "northern-rhovanion"),
    moveAllArmy ("far-harad", "near-harad")),
  fp ().eventDieCard ("Celeborn's Galadhrim",
    recruitEliteUnit ("lorien", "elves"),
    drawCards ("Riders of Theoden")),
  s ().eventDieCard ("Nazgul Search",
    moveNazgul ("minas-morgul", "old-ford"),
    revealFellowship ("carrock")),
  fp ().pass (),
  s ().musterArmyDie (attack ("northern-rhovanion", "old-forest-road", regular ("sauron", 9), elite ("sauron"), nazgul (2))),
  s ().battleStory (noCombatCard ()),
  fp ().battleStory (combatCard ("The Power of Tom Bombadil")),
  fp (time).battleStory (rollCombatDice (6)),
  s ().battleStory (rollCombatDice (4, 2, 3, 4, 6)),
  s ().battleStory (eliminateRegularUnit ("northern-rhovanion", "sauron")),
  fp ().battleStory (eliminateRegularUnit ("old-forest-road", "north")),
  s ().battleStory (moveAllArmy ("northern-rhovanion", "old-forest-road")),
  fp ().actionToken ("draw-card", drawCards ("Thranduil's Archers")),
  s ().musterDie (advanceNation ("southrons")),
  fp ().musterArmyDie (advanceNation ("elves")),
  s ().eventDieCard ("Half-orcs and Goblin-men", recruitEliteUnit ("old-forest-road", "isengard")),
  fp ().willOfTheWestDie (recruitEliteUnit ("woodland-realm", "elves")),
  // Turn 4
  s (time).phaseStory (drawCards ("Isildur's Bane", "Hill-trolls")),
  fp ().phaseStory (drawCards ("The Ents Awake: Huorns", "The Red Arrow")),
  s ().huntAllocation (1),
  fp (time).rollActionDice ("muster", "muster-army", "muster-army", "will-of-the-west"),
  s ().rollActionDice ("eye", "eye", "eye", "event", "muster-army", "army"),
  fp ().musterDie (recruitEliteUnit ("woodland-realm", "elves")),
  s ().armyDie (attack ("dimrill-dale", "lorien", regular ("sauron", 5), regular ("isengard", 4), elite ("sauron"), nazgul ())),
  fp ().battleStory (retreatIntoSiege ("lorien")),
  s ().phaseStory (moveAllArmy ("dimrill-dale", "lorien")),
  fp ().musterArmyDie (recruitEliteUnit ("woodland-realm", "elves")),
  s ().eventDieCard ("Hill-trolls",
    eliminateRegularUnit ("lorien", "sauron", 2),
    recruitEliteUnit ("lorien", "sauron", 2)),
  fp ().musterArmyDie (advanceNation ("north")),
  s ().musterArmyDie (advanceNation ("southrons")),
  fp ().willOfTheWestDie (advanceNation ("north")),
  // Turn 5
  fp (time).phaseStory (
    drawCards ("I Will Go Alone", "The Last Battle"),
    discardCards ("Kindred of Glorfindel", "The Ents Awake: Huorns")),
  s ().phaseStory (
    drawCards ("The Black Captain Commands", "Corsairs of Umbar"),
    discardCards ("Wormtongue")),
  s ().huntAllocation (0),
  fp (time).rollActionDice ("muster", "will-of-the-west", "will-of-the-west", "character"),
  s ().rollActionDice ("muster", "muster-army", "event", "muster", "army", "character", "muster-army"),
  fp ().willOfTheWestDie (hideFellowship ()),
  s ().armyDie (
    moveArmy ("old-forest-road", "carrock", regular ("sauron")),
    moveArmy ("near-harad", "umbar", regular ("southrons", 5), elite ("southrons", 2))),
  fp ().musterDie (recruitEliteUnit ("dale", "north")),
  s ().eventDieCard ("The Day Without Dawn", discardDice ("free-peoples", "will-of-the-west")),
  fp ().pass (),
  s ().musterDie (playCharacter ("orthanc", "saruman")),
  fp ().pass (),
  s ().musterDie (playCharacter ("old-forest-road", "the-witch-king")),
  fp ().pass (),
  s ().musterArmyDie (attack ("old-forest-road", "dale", regular ("sauron", 7), elite ("sauron"), elite ("isengard"), nazgul (2), character ("the-witch-king"))),
  s ().battleStory (noCombatCard ()),
  fp ().battleStory (combatCard ("The Red Arrow")),
  fp ().combatCardReaction ("The Red Arrow", moveAllArmy ("dale", "erebor")),
  s ().battleStory (moveAllArmy ("old-forest-road", "dale")),
  fp ().pass (),
  s ().musterArmyDieCard ("Corsairs of Umbar", attack ("umbar", "dol-amroth", regular ("southrons", 7), elite ("southrons", 2))),
  fp ().battleStory (retreatIntoSiege ("dol-amroth")),
  s ().battleStory (moveArmy ("umbar", "dol-amroth", regular ("southrons", 7), elite ("southrons", 2))),
  fp ().characterDie (moveFelloswhip ()),
  s ().characterDieCard ("The Black Captain Commands",
    moveCharacters ("dale", "dol-amroth", "the-witch-king"),
    moveNazgul ("dale", "dol-amroth", 2),
    moveNazgul ("old-ford", "dol-amroth"),
    attack ("dol-amroth", "dol-amroth", regular ("southrons", 7), elite ("southrons", 2), nazgul (3), character ("the-witch-king"))),
  s ().battleStory (combatCard ("Return to Valinor")),
  fp ().battleStory (combatCard ("The Last Battle")),
  s (time).battleStory (rollCombatDice (5, 1, 4)),
  fp ().battleStory (rollCombatDice (2, 4, 4)),
  s ().battleStory (reRollCombatDice (5)),
  s ().battleStory (eliminateRegularUnit ("dol-amroth", "southrons", 2)),
  fp ().battleStory (eliminateRegularUnit ("dol-amroth", "gondor", 3)),
  s ().characterReaction ("the-witch-king", drawCards ("Orcs Multiplying Again")),
  // Turn 6 30:00
  fp (time).phaseStory (drawCards ("There and Back Again", "Grimbeorn the Old, Son of Beorn")),
  s ().phaseStory (drawCards ("Grond, Hammer of the Unnderworld", "Shadows on the Misty Mountains")),
  fp ().phaseStory (declareFellowship ("old-forest-road")),
  s ().huntAllocation (1),
  s (time).rollActionDice ("eye", "muster", "army", "event", "muster", "muster", "character", "muster-army"),
  fp ().rollActionDice ("character", "event", "character", "muster"),
  fp ().characterDie (moveFelloswhip ()),
  s ().huntStory (rollHuntDice (2, 6)),
  s ().huntStory (drawHuntTile ("2")),
  fp ().huntStory (eliminateCharacter ("legolas"), changeGuide ("gimli")),
  s ().skipCardReaction ("Worn with Sorrow and Toil"),
  s ().characterDie (
    moveCharacters ("dol-amroth", "orthanc", "the-witch-king"),
    moveNazgul ("dol-amroth", "old-forest-road"),
    moveNazgul ("dol-amroth", "southern-rhovanion"),
    moveNazgul ("dol-amroth", "noman-lands")
  ),
  fp ().pass (),
  s ().musterDie (
    recruitRegularUnit ("orthanc", "isengard"),
    recruitRegularUnit ("north-dunland", "isengard"),
    recruitRegularUnit ("south-dunland", "isengard")
  ),
  fp ().pass (),
  s ().musterDie (
    eliminateRegularUnit ("orthanc", "isengard", 2),
    recruitEliteUnit ("orthanc", "isengard", 2),
  ),
  fp ().pass (),
  s ().musterDie (
    eliminateRegularUnit ("orthanc", "isengard", 2),
    recruitEliteUnit ("orthanc", "isengard", 2),
  ),
  fp ().musterElvenRingDie ("narya",
    moveAllArmy ("fords-of-isen", "helms-deep"),
    moveAllArmy ("westemnet", "helms-deep")
  ),
  s ().armyDie (
    moveArmy ("orthanc", "fords-of-isen", regular ("isengard"), elite ("isengard", 5), character ("the-witch-king")),
    moveAllArmy ("south-rhun", "east-rhun")
  ),
  fp ().characterDie (moveFelloswhip ()),
  s ().huntStory (rollHuntDice (2, 2)),
  s ().huntStory (reRollHuntDice (1)),
  s ().musterArmyDie (attack ("fords-of-isen", "helms-deep", regular ("isengard"), elite ("isengard", 4), character ("the-witch-king"))),
  fp ().battleStory (retreatIntoSiege ("helms-deep")),
  s ().battleStory (moveAllArmy ("fords-of-isen", "helms-deep")),
  fp ().eventDieCard ("I Will Go Alone", separateCompanions ("druadan-forest", "boromir"), healFellowship (1)),
  s ().eventDieCard ("Isildur's Bane", drawHuntTile ("0r")),
  fp ().huntStory (revealFellowship ("southern-rhovanion")),
  // Turn 7 42:05
  s (time).phaseStory (drawCards ("The Nazgul Strike", "Olog-hai")),
  fp ().phaseStory (
    drawCards ("Bilbo's Song", "Paths of the Woses"),
    discardCards ("Paths of the Woses")),
  s ().huntAllocation (1),
  s (time).rollActionDice ("event", "character", "muster", "muster", "event", "character", "muster", "army"),
  fp ().rollActionDice ("character", "character", "muster", "character"),
  fp ().characterDie (hideFellowship ()),
  s ().eventDieCard ("Olog-hai", recruitEliteUnit ("helms-deep", "sauron")),
  fp ().characterDie (moveFelloswhip ()),
  s ().huntStory (rollHuntDice (6)),
  s ().huntStory (drawHuntTile ("1r")),
  fp ().huntStory (corruptFellowship (1)),
  fp ().huntStory (revealFellowship ("noman-lands")),
  s ().eventDie (drawCards ("A New Power is Rising")),
  fp ().pass (),
  s ().armyDieCard ("The Fighting Uruk-hai", attack ("helms-deep", "helms-deep", elite ("sauron"), elite ("isengard", 5), character ("the-witch-king"))),
  s ().battleStory (combatCard ("Grond, Hammer of the Unnderworld")),
  fp ().battleStory (noCombatCard ()),
  s ().combatCardReaction ("Grond, Hammer of the Unnderworld", forfeitLeadership (character ("the-witch-king"))),
  s (time).battleStory (rollCombatDice (2, 5, 5, 4, 6)),
  fp ().battleStory (rollCombatDice (4, 6, 4)),
  s (time).battleStory (reRollCombatDice (2, 2, 4, 5)),
  fp ().battleStory (reRollCombatDice (2)),
  s ().battleStory (
    eliminateRegularUnit ("helms-deep", "isengard")
  ),
  fp ().battleStory (
    eliminateEliteUnit ("helms-deep", "rohan"),
    recruitRegularUnit ("helms-deep", "rohan")
  ),
  s ().battleStory (continueBattle ("helms-deep")),
  s ().characterReaction ("the-witch-king", drawCards ("The Breaking of the Fellowship")),
  s ().battleStory (noCombatCard ()),
  fp ().battleStory (noCombatCard ()),
  s (time).battleStory (rollCombatDice (2, 6, 3, 2, 6)),
  fp ().battleStory (rollCombatDice (2, 4, 4, 2, 3)),
  s (time).battleStory (reRollCombatDice (2, 5, 5)),
  fp ().battleStory (reRollCombatDice (1)),
  fp ().battleStory (eliminateRegularUnit ("helms-deep", "rohan", 2)),
  s ().battleStory (continueBattle ("helms-deep")),
  s ().battleStory (noCombatCard ()),
  fp ().battleStory (noCombatCard ()),
  s (time).battleStory (rollCombatDice (4, 2, 4, 1, 2)),
  fp ().battleStory (rollCombatDice (1, 2, 6)),
  s (time).battleStory (reRollCombatDice (1, 5, 5, 5, 4)),
  fp ().battleStory (reRollCombatDice (4)),
  s ().battleStory (
    eliminateEliteUnit ("helms-deep", "isengard"),
    recruitRegularUnit ("helms-deep", "isengard")
  ),
  s ().battleStory (
    continueBattle ("helms-deep"),
    eliminateEliteUnit ("helms-deep", "isengard"),
    recruitRegularUnit ("helms-deep", "isengard")
  ),
  s ().battleStory (noCombatCard ()),
  fp ().battleStory (noCombatCard ()),
  s (time).battleStory (rollCombatDice (3, 2, 3, 1, 5)),
  fp ().battleStory (rollCombatDice (2, 4, 6)),
  s (time).battleStory (reRollCombatDice (6, 4, 2, 6, 5)),
  fp ().battleStory (reRollCombatDice (5)),
  s ().battleStory (
    eliminateEliteUnit ("helms-deep", "isengard"),
  ),
  fp ().battleStory (
    eliminateRegularUnit ("helms-deep", "rohan", 2),
  ),
  s ().battleStory (
    continueBattle ("helms-deep"),
    eliminateEliteUnit ("helms-deep", "isengard"),
    recruitRegularUnit ("helms-deep", "isengard")
  ),
  s ().battleStory (noCombatCard ()),
  fp ().battleStory (combatCard ("Riders of Theoden")),
  s (time).battleStory (rollCombatDice (6, 3, 2)),
  fp ().battleStory (rollCombatDice (5)),
  s ().battleStory (
    eliminateEliteUnit ("helms-deep", "sauron"),
    recruitRegularUnit ("helms-deep", "sauron")
  ),
  fp ().battleStory (
    eliminateRegularUnit ("helms-deep", "rohan"),
    eliminateLeader ("helms-deep", "rohan")
  ),
  fp ().musterDie (
    recruitRegularUnit ("edoras", "rohan"),
    recruitRegularUnit ("westemnet", "rohan"),
  ),
  s ().characterDieCard ("The Breaking of the Fellowship", drawHuntTile ("3")),
  fp ().huntStory (
    separateCompanions ("noman-lands", "gimli", "meriadoc", "peregrin"),
    changeGuide ("gollum")),
  fp ().pass (),
  s ().characterDie (attack ("helms-deep", "westemnet", regular ("isengard", 3), regular ("sauron"), elite ("isengard"), character ("the-witch-king"))),
  s ().battleStory (noCombatCard ()),
  fp ().battleStory (noCombatCard ()),
  s (time).battleStory (rollCombatDice (6, 6, 6, 5, 6)),
  fp ().battleStory (rollCombatDice (4)),
  fp ().battleStory (eliminateRegularUnit ("westemnet", "rohan")),
  s ().battleStory (moveArmy ("helms-deep", "westemnet", regular ("isengard", 3), elite ("isengard"), character ("the-witch-king"))),
  fp ().pass (),
  s ().musterDie (recruitEliteUnit ("north-rhun", "southrons")),
  fp ().pass (),
  s ().musterDie (recruitEliteUnit ("north-rhun", "southrons")),
  fp ().characterDie (hideFellowship ()),
  s ().musterElvenRingDie ("narya", attack ("westemnet", "edoras", regular ("isengard", 3), elite ("isengard"), character ("the-witch-king"))),
  s ().battleStory (noCombatCard ()),
  fp ().battleStory (noCombatCard ()),
  s (time).battleStory (rollCombatDice (5, 2, 3, 4)),
  fp ().battleStory (rollCombatDice (3)),
  s ().battleStory (reRollCombatDice (1, 1, 2)),
  s ().battleStory (continueBattle ("edoras")),
  fp ().battleStory (retreat ("edoras", "folde")),
  s ().battleStory (moveAllArmy ("westemnet", "edoras")),
  // Turn 8 54:32
  fp (time).phaseStory (
    drawCards ("Horns of Gondor", "Fear! Fire! Foes!"),
    discardCards ("Horns of Gondor")),
  s ().phaseStory (drawCards ("Dreadful Spells", "Musterings of Long-planned War")),
  fp ().phaseStory (notDeclareFellowship ()),
  s ().huntAllocation (1),
  s (time).rollActionDice ("eye", "army", "muster-army", "army", "muster-army", "character", "eye", "muster"),
  fp ().rollActionDice ("event", "character", "character", "event"),
  fp ().characterDie (moveFelloswhip ()),
  s ().huntStory (rollHuntDice (5, 1, 2)),
  s ().huntStory (reRollHuntDice (2)),
  s ().armyDie (attack ("edoras", "folde", regular ("isengard", 3), elite ("isengard"), character ("the-witch-king"))),
  s ().battleStory (noCombatCard ()),
  fp ().battleStory (noCombatCard ()),
  s (time).battleStory (rollCombatDice (5, 6, 6, 5)),
  fp ().battleStory (rollCombatDice (2)),
  fp ().battleStory (eliminateRegularUnit ("folde", "rohan")),
  s ().battleStory (moveAllArmy ("edoras", "folde")),
  fp ().characterDie (moveFelloswhip ()),
  s ().huntStory (rollHuntDice (5, 4, 1)),
  s ().huntStory (reRollHuntDice (1)), // missing in the video
  s ().huntStory (drawHuntTile ("2r")),
  fp ().characterReaction ("gollum", corruptFellowship (1), revealFellowship ("morannon")),
  s ().huntStory (drawHuntTile ("er")),
  fp ().huntStory (corruptFellowship (1))

];

export const fpTokens: WotrActionToken[] = ["draw-card", "political-advance"];

function fp (t?: number) { if (!t) { t = time++; } return new WotrFreePeoplesStoryComposer (t); }
function s (t?: number) { if (!t) { t = time++; } return new WotrShadowStoryComposer (t); }
