import { BaronyAction, BaronyColor, BaronyLandPiece, BaronyLandType, BaronyPawnType } from "./models";

export const baronyLandTypes: BaronyLandType[] = ["fields", "forest", "lake", "mountain", "plain"];
export const baronyColors: BaronyColor[] = ["blue", "green", "red", "yellow"];
export const baronyPawnTypes: BaronyPawnType[] = ["city", "knight", "stronghold", "village"];
export const baronyActions: BaronyAction[] = ["recruitment", "movement", "construction", "newCity", "expedition", "nobleTitle"];
export const baronyLandPieces: BaronyLandPiece[] = [
  { 1: "mountain", 2: "mountain", 3: "mountain", quantity: 1 },
  { 1: "mountain", 2: "mountain", 3: "forest", quantity: 1 },
  { 1: "mountain", 2: "mountain", 3: "plain", quantity: 1 },
  { 1: "mountain", 2: "mountain", 3: "fields", quantity: 1 },
  { 1: "mountain", 2: "mountain", 3: "lake", quantity: 2 },
  { 1: "mountain", 2: "forest", 3: "forest", quantity: 1 },
  { 1: "mountain", 2: "forest", 3: "plain", quantity: 0 },
  { 1: "mountain", 2: "forest", 3: "fields", quantity: 0 },
  { 1: "mountain", 2: "forest", 3: "lake", quantity: 1 },
  { 1: "mountain", 2: "plain", 3: "forest", quantity: 1 },
  { 1: "mountain", 2: "plain", 3: "plain", quantity: 1 },
  { 1: "mountain", 2: "plain", 3: "fields", quantity: 0 },
  { 1: "mountain", 2: "plain", 3: "lake", quantity: 0 },
  { 1: "mountain", 2: "fields", 3: "forest", quantity: 1 },
  { 1: "mountain", 2: "fields", 3: "plain", quantity: 1 },
  { 1: "mountain", 2: "fields", 3: "fields", quantity: 1 },
  { 1: "mountain", 2: "fields", 3: "lake", quantity: 0 },
  { 1: "mountain", 2: "lake", 3: "forest", quantity: 0 },
  { 1: "mountain", 2: "lake", 3: "plain", quantity: 1 },
  { 1: "mountain", 2: "lake", 3: "fields", quantity: 1 },
  { 1: "mountain", 2: "lake", 3: "lake", quantity: 0 },
  { 1: "forest", 2: "forest", 3: "forest", quantity: 2 },
  { 1: "forest", 2: "forest", 3: "plain", quantity: 1 },
  { 1: "forest", 2: "forest", 3: "fields", quantity: 1 },
  { 1: "forest", 2: "forest", 3: "lake", quantity: 2 },
  { 1: "forest", 2: "plain", 3: "plain", quantity: 1 },
  { 1: "forest", 2: "plain", 3: "fields", quantity: 1 },
  { 1: "forest", 2: "plain", 3: "lake", quantity: 0 },
  { 1: "forest", 2: "fields", 3: "plain", quantity: 0 },
  { 1: "forest", 2: "fields", 3: "fields", quantity: 1 },
  { 1: "forest", 2: "fields", 3: "lake", quantity: 0 },
  { 1: "forest", 2: "lake", 3: "plain", quantity: 1 },
  { 1: "forest", 2: "lake", 3: "fields", quantity: 1 },
  { 1: "forest", 2: "lake", 3: "lake", quantity: 0 },
  { 1: "plain", 2: "plain", 3: "plain", quantity: 2 },
  { 1: "plain", 2: "plain", 3: "fields", quantity: 1 },
  { 1: "plain", 2: "plain", 3: "lake", quantity: 2 },
  { 1: "plain", 2: "fields", 3: "fields", quantity: 1 },
  { 1: "plain", 2: "fields", 3: "lake", quantity: 1 },
  { 1: "plain", 2: "lake", 3: "fields", quantity: 0 },
  { 1: "plain", 2: "lake", 3: "lake", quantity: 0 },
  { 1: "fields", 2: "fields", 3: "fields", quantity: 1 },
  { 1: "fields", 2: "fields", 3: "lake", quantity: 2 },
  { 1: "fields", 2: "lake", 3: "lake", quantity: 0 },
  { 1: "lake", 2: "lake", 3: "lake", quantity: 0 },
];
